### PR TITLE
Show bridge cost on hover

### LINKED ISSUE #541: Building bridges should show the cost
When building roads or reservoirs, dragging the mouse shows the cost of building:

image

image

This is not the case with bridges:

image

Bridges are quite expensive, taking 100 denarii per tile for a Ship Bridge, and 40 denarii for a Low Bridge, so I think it would be nice to see how much would it cost. The bridge in the picture costs 1400 for example.

**Edit:** I am now seeing that the cost is only shown when the mouse click is pressed and hold, for every building. I'm guessing this is the reason bridges don't show the cost, because they are not "draggable". However, I tend to now favor showing costs for all buildings even when just hovering the mouse and not clicking. Of course, I can "drag away" to see the cost and not build the bridge, but it is not really intuitive. 

What do you think?

### PR DESCRIPTION
**Pull request by crudelios**
Fix #541

### CODE REVIEW

**Comment by bvschaik** [comment]
Bug found:

1. Let the game run
1. Select bridge from the build menu
1. Hover over a suitable location

Notice that the game now pauses like it does when you try to drag roads.

**Comment by crudelios** [comment]
Fixed, thanks 👍

**Comment by bvschaik** [comment]
Found another bug 😉  (They're getting more obscure now)

Steps:
1. Select bridge
2. Find a spot where it can be placed
3. Position the map in such a way that you can move your mouse from the good spot to the sidebar without hitting another tile
4. Select any build, a school or something
5. Hover over the map - school will display the cost of the bridge

Solution is pretty simple: in `building_construction_set_type()` we should also reset `data.cost` to 0.

**Comment by crudelios** [comment]
That's a really obscure one, well spotted!

**Review by bvschaik — APPROVED** [review]

**Pull request merged**
