### PR TITLE
Fix vertical font positioning on small size accented chars on tooltips

### PR DESCRIPTION
**Pull request by crudelios**
Before:

before

After:

after

This was only visible on tooltips, but it was distracting so I fixed it. Checked both portuguese and german languages. @bvschaik can you get me a french version of `c3.eng` please?

### CODE REVIEW

**Comment by crudelios** [comment]
@411752230 can you please test the messages in Chinese (mission briefing, help menus and messages like "emperor requests goods") to see if the text is ok? If this is working well, you shouldn't spot any differences 😉

Link to Julius build:  https://ci.appveyor.com/api/buildjobs/wr48tcbglfu7rn6p/artifacts/build%2Fjulius.exe

Thanks!!

**Comment by 411752230** [comment]
> @411752230 can you please test the messages in Chinese (mission briefing, help menus and messages like "emperor requests goods") to see if the text is ok? If this is working well, you shouldn't spot any differences 😉
> 
> Link to Julius build: https://ci.appveyor.com/api/buildjobs/wr48tcbglfu7rn6p/artifacts/build%2Fjulius.exe
> 
> Thanks!!

Gladly

**Comment by 411752230** [comment]
> @411752230 can you please test the messages in Chinese (mission briefing, help menus and messages like "emperor requests goods") to see if the text is ok? If this is working well, you shouldn't spot any differences 😉
> 
> Link to Julius build: https://ci.appveyor.com/api/buildjobs/wr48tcbglfu7rn6p/artifacts/build%2Fjulius.exe
> 
> Thanks!!

Works fine! I saw mission briefing, help menus and messages like "emperor requests goods as you said. No difference found.

**Comment by bvschaik** [comment]
French update containing c3.eng: https://bintray.com/bvschaik/caesar3-patches/french/1.0.1.0

**Comment by crudelios** [comment]
Tested and working on the french version!

**Comment by bvschaik** [comment]
Polish version also looks good.

**Pull request merged**
