### PR TITLE
Add a "game speed" information to the top menu

### PR DESCRIPTION
**Pull request by crudelios**
It sits above the `Overlays` panel and only appears when the resolution width is `>= 1150`.

top_menu_game_speed

Right-clicking on it will open the `Speed settings` menu.

### CODE REVIEW

**Comment by 411752230** [comment]
Looks good but strange to me. Only one reason: a temporary notifying message without need to be permanent and occupy some space in the top bar.

**Comment by crudelios** [comment]
> Only one reason: a temporary notifying message without need to be permanent and occupy some space in the top bar.

As I said, I disagree and I think a the permanent information is useful.

Also as I said on #244, I think both can be used. Show only notifications on lower resolutions, show the permanent display on higher resolutions.

**Comment by 411752230** [comment]
> > Only one reason: a temporary notifying message without need to be permanent and occupy some space in the top bar.
> 
> As I said, I disagree and I think a the permanent information is useful.
> 
> Also as I said on #244, I think both can be used. Show only notifications on lower resolutions, show the permanent display on higher resolutions.

Well. As @bvschaik said, an external program might be added to implement some extra features. Anyway, i think this could be added into the program as one of the optional preferences, while the message bar could be resident for its consistency to the Sierra city-building sequels.

**Comment by crudelios** [comment]
Due to #281, I'm closing this.

**Pull request closed without merging**
