### PR TITLE
Audio fixes, and set rate to 44100

### PR DESCRIPTION
**Pull request by crudelios**
* Fix audio clicks during video playback at 44100 audio frequency for SDL >= 2.0.7.
* Fix volume of videos.
* Set global audio frequency rate to 44100.

### CODE REVIEW

**Comment by bvschaik** [comment]
I'll have a look at the SDL_mixer source this weekend to see how they do stuff without AudioStreams.

**Comment by crudelios** [comment]
They use AudioStreams :P That's how I learned about them.

**Comment by devnoname120** [comment]
I've just tested on the PS Vita with the https://github.com/bvschaik/julius/pull/218 changes and it seems to work fine as well. I've noticed there can be a bit of stuttering at the end of the video but it doesn't happen every time. (And it might just be bad luck, not certain it's caused by this change).

**Comment by crudelios** [comment]
@devnoname120 are you referring to this PR regarding the stutters? Do you mean it doesn't happen just with #208?

Also, with #208 do you hear any clicks in the audio? It's more noticeable in some videos than others...

**Comment by bvschaik** [comment]
I'm wondering about this as well. PR #208 can cause audio stutters if the decoder cannot keep up with the video playback and lags more than one second behind. The stuttering should happen more often on longer videos, such as `lose_game.smk`, could you confirm that?
Maybe I should implement frame skipping if the decoding process cannot keep up.

**Pull request merged**
