### PR TITLE
Update lang.c

### PR DESCRIPTION
**Pull request by eugenikus8**
eng-rus, rus-eng map editor
Bilingual map editor with the ability to switch the editor language through the settings menu.
Russian localization files must be located in a separate folder, for example rus (caesar3/rus)
[rus.zip](https://github.com/user-attachments/files/16059263/rus.zip)

### CODE REVIEW

**Comment by eugenikus8** [comment]
[rus.zip](https://github.com/user-attachments/files/15993717/rus.zip)

**Comment by bvschaik** [comment]
The code: looks good to me 👍 

Will you allow me to add the Russian files to [the Editor wiki page](https://github.com/bvschaik/julius/wiki/Editor)? With attribution of course; I'm guessing you translated the editor yourself?

**Comment by eugenikus8** [comment]
Yes, of course you can take files. The translation from the 1C company is taken as a basis. I just made some changes so that the lines match the English locale. And corrected translation errors. So I didn't formally translate anything.

**Review by bvschaik — APPROVED** [review]

**Comment by bvschaik** [comment]
Thanks! I added the Russian editor to the wiki.

**Pull request merged**
