### PR TITLE
Add metainfo file; FreeDesktop spec compliance fixes

### PR DESCRIPTION
**Pull request by barthalion**

### CODE REVIEW

**Comment by crudelios** [comment]
Just for consistency: in my Android build I kept the app name as `bvschaik.julius`. Here the app id is `com.github.bvschaik.julius`.

I know both are independant, but I think the id should still be the same. Which one is best to keep, I have no idea.

**Comment by barthalion** [comment]
I used `com.github.bvschaik.julius` as it's "real" reverse DNS. While nothing enforces it, at Flathub we expect that domain to exist.

**Comment by barthalion** [comment]
Seems AppImage exits with 0 even when it actually failed: https://travis-ci.org/bvschaik/julius/jobs/642802514?utm_medium=notification&utm_source=github_status

**Comment by bvschaik** [comment]
Let's use package name `com.github.bvschaik.julius` for both Android and flatpak, to keep things consistent.

**Pull request merged**
