### PR TITLE
Version information fine tuning (#79)

### PR DESCRIPTION
**Pull request by siredmar**
Version information containing git version if cmake could extract that information. If not a fallback string is being printed

Example git can be found by cmake: 
``./julius                          ``
``INFO: Built with git commit: v1.0.0-27-g86939162e8-dirty``

Example git cannot be found by cmake:
``./julius                                 ``
``INFO: Built with git commit: unknown (please install git and/or add it to PATH to get build information)``

### CODE REVIEW

**Comment by bvschaik** [comment]
One problem I see with this: release versions. Packagers download the .zip without any git information and build the package from there. How should we deal with that?

**Comment by siredmar** [comment]
If you do a release compile without any git information, you need to maintain a extra version information within the codebase e.g. version_release.h that contains the release version.
If this is the way you want to go, its a minor thing to implement. But keep in mind, that you have to maintain it manually.

I would either then print the release_version information or the git related version information on startup.
Current release version is 1.0.0, right?

One thing to ask: Do the automatically build windows versions contain the git information?
If so, standard users who don't compile it manually won't be able to tell with which git commit the software was built.

**Comment by siredmar** [comment]
@bvschaik please review the proposal i've made. However, I have to consider that you have to maintain the version number manually. :-/

**Comment by crudelios** [comment]
Strangely enoguh, for me the built packages from appveyor don't show anything at all, not even the `Built with version` part. I made sure to download the artifact from the proper pull request.

**Comment by shirakaba** [comment]
Sorry that I don't have time to read/discuss details at the moment, but if I'm understanding the situation correctly (CMake shouldn't depend on git) there may be a way to solve this by using a pre-commit hook to save a commit name to a text file.

```sh
# Here's an example script of how to get the latest tag
git describe --always --tag --abbrev=0 > git_tag.txt
```

That code

**Comment by jdmillard** [comment]
Manually maintaining the version in a 'version.h' for a single project really isn't that hard, especially when there is a sole repo owner as is our case.

You might ask : what about folks using nightly builds and how to communicate version numbers when bugs are found? I think in that case a nightly build is identified by its date and/or a checksum (as well as the version.h which could be printed to console).

**Comment by siredmar** [comment]
> Sorry that I don't have time to read/discuss details at the moment, but if I'm understanding the situation correctly (CMake shouldn't depend on git) there may be a way to solve this by using a pre- or post-commit hook to save a commit name to a text file.
> 
> ```shell
> # Here's an example script of how to get the latest tag
> git describe --always --tag --abbrev=0 > git_tag.txt
> 
> # A similar script could be used to write in the commit hash.
> ```

I have tried that right now and finished with my tests.
What i did was: put post hooks in merge, checkout and commit that generates a version.h file.
If developers all have those hooks installed this might work just fine. 
Problem is however that version.h file gets generated after the commit/merging/checkout is done. This means you have a dirty tree. One needs to check in that modified file in an extra commit generating a new version.h and so on.
Putting this version.h in the .gitignore file is working when getting the source via git. But when downloading the zip file, this file is missing obviosly.

So i guess not the way to go? @shirakaba maybe i have done something wrong or did not use the correct hook. Maybe you can share any further information.

**Comment by bvschaik** [comment]
Actually, there is already a version in the source code for the windows build: [res/version.rc](res/version.rc).

I don't like the idea of a version.h that gets updated on every commit, even if it's automated.

What I'd like to have:
A single file where I can add the version number and a boolean flag whether it's an official release or not. Ideally, I'd like to generate both `res/version.rc` and some sort of `version.h` from that file.
Releasing a version then consists of 3 easy steps:
- Update version/release flag on master
- Create a tag for that version
- Update release flag to false on master

Now, what to print:
1. For release versions, Julius can print something simple like "Julius release v1.0.1"
1. For non-release versions without git directory: "Julius unknown development version (please install git)"
1. For non-release versions with git directory present: "Julius development v1.0.1-$git_commit" (I don't think we need the "tag + _n_ commits" part, perhaps the dirty flag is useful here)

**Comment by bvschaik** [comment]
@crudelios The Windows build doesn't write anything to the `julius-log.txt` because the log message is written before log output is redirected to that file. That needs to be fixed.

@siredmar Please no actual code in `.h` files: if you include the `.h` file in multiple source files, you're toast. And please keep the formatting consistent with the rest of the project (whitespace, curly braces position, naming of include guards, etc).

**Comment by shirakaba** [comment]
@siredmar 

> Problem is however that version.h file gets generated after the commit/merging/checkout is done. This means you have a dirty tree. One needs to check in that modified file in an extra commit generating a new version.h and so on.
> Putting this version.h in the .gitignore file is working when getting the source via git. But when downloading the zip file, this file is missing obviosly.
> 
> So i guess not the way to go? @shirakaba maybe i have done something wrong or did not use the correct hook. Maybe you can share any further information.

I suppose it makes sense that the change doesn't get committed. Okay, assuming a pre-commit hook, maybe the hook just needs to also include a procedure for adding the updated file into the commit (could be as simple as `git add git_tag.txt`..?). I'm no expert on git hooks, unfortunately.

**Comment by shirakaba** [comment]
> What I'd like to have:
> A single file where I can add the version number and a boolean flag whether it's an official release or not. Ideally, I'd like to generate both `res/version.rc` and some sort of `version.h` from that file.
> Releasing a version then consists of 3 easy steps:
> 
> * Update version/release flag on master
> * Create a tag for that version
> * Update release flag to false on master

Is this currently a manual operation? Would a release script be helpful?

I use this script to help with CI on some projects. It includes my process of writing a tag to a file. Of course that part could be removed, and the required toggling of the release flag could be introduced.

For inspiration:

```sh
# Example of tagging a commit as "v1.1.1"
./tag.sh "v1.1.1"
``` 

```sh
#!/usr/bin/env bash

echo $1 > ./git_tag.txt
git add ./git_tag.txt
git commit -am "Tag as $1"
git push origin master
git tag $1 master
git push origin $1
```

**Comment by bvschaik** [comment]
> Is this currently a manual operation? Would a release script be helpful?

Currently I have made only one release (which was a bit of trial and error), so I have no real release procedure as of yet... perhaps your script will be useful for that.

**Pull request closed without merging**
