### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by Keriew**

### CODE REVIEW

**Comment by Keriew** [comment]
Oops, forgot commit that one change before the PR.

**Comment by crudelios** [comment]
Thanks!

Can you also translate the text `Enable military sidebar`, please? Not as an actual change to the files, but as a comment, so I can add it to the military sidebar PR.

**Comment by Keriew** [comment]
Sure. "Włącz boczny panel wojskowy."

**Comment by bvschaik** [comment]
Nice!
Another translation request: "Caesar III assignment editor" - in the Polish language files this is the Polish version of "internal".

**Comment by Keriew** [comment]
That would be "Edytor misji" (hard to keep Caesar 3 there in proper form and still have it sound natural) Thank you!

**Pull request merged**
