### PR TITLE
Upload PS Vita artifacts to bintray

### PR DESCRIPTION
**Pull request by devnoname120**
Before this works you need to:
- [Sign in to Bintray using GitHub](https://bintray.com/signup/oss).
- Click on Add New Repository [in this page](https://bintray.com/bvschaik).
- [Go to your profile](https://bintray.com/profile/edit) and get the API key.
- [Install the Travis client](https://github.com/travis-ci/travis.rb#installation) in order to encrypt it.
- Encrypt it by executing `travis encrypt YOUR_API_KEY_HERE -r bvschaik/julius`.
- Fill it in `.travis.yml` at the line `secure: false # Fill in here your Bintray encrypted API key!`

You can see it in action on [this branch](https://github.com/devnoname120/julius/tree/bintray). And [here](https://bintray.com/devnoname120/julius/vita/_latestVersion) is an example of a download.

### CODE REVIEW

**Comment by crudelios** [comment]
Of we're going to have downloadable Vita and Switch versions, I think we should also add some instructions for people to install those versions and warn that hacking the console is needed.

**Comment by devnoname120** [comment]
I agree, in a future pull request though.

**Comment by crudelios** [comment]
> I agree, in a future pull request though.

Agreed.

**Comment by devnoname120** [comment]
I like the old table style better, though.

**Comment by bvschaik** [comment]
PR has been merged (and then built upon), see commit e64c2034c193bf9c95f17b5d341a524d93031fa5

**Pull request closed without merging**
